export const APP_POP_SNACK_BAR_MESSAGE = 'APP_POP_SNACK_BAR_MESSAGE'
export const APP_PUSH_SNACK_BAR_MESSAGE = 'APP_PUSH_SNACK_BAR_MESSAGE'
export const APP_SET_IS_SNACK_BAR_OPEN = 'APP_SET_IS_SNACK_BAR_OPEN'
export const APP_SET_USER = 'APP_SET_USER'